### PR TITLE
Support passing custom types by value into JS imports

### PR DESCRIPTION
**Pull request by Healthire**
As mentioned in #69

### CODE REVIEW

**Comment by alexcrichton** [comment]
Awesome, thanks!

**Comment by nkoehring** [comment]
I still didn't really get this to work. I can export the struct but don't see anything in the wasm exports. I tried to create a static instance with lazy_static and use that in an exported function, which compiles but throws an error (unreachable used). What am I doing wrong? Does the struct and its implementations (like ::new) need to be public?

**Comment by alexcrichton** [comment]
@nkoehring can you share the code you're with? I may be able to help out if I can poke around!

**Comment by nkoehring** [comment]
@alexcrichton thanks for your reply! In the meantime I found out that it is the Rand crate that I used in `::new`. So my question actually changed to "how to make crates available".

**Comment by alexcrichton** [comment]
@nkoehring hm so you mean making existing crates available to JS? Currently that requires wrapping them in `#[wasm_bindgen]` to have an interface that JS can use as well

**Comment by nkoehring** [comment]
So the crate itself would have to be changed, I guess? Anyways, I solved the problem by using Javascripts random function.

**Comment by alexcrichton** [comment]
Yeah at this time it'd require upstream changes or a local wrapper

**Pull request merged**
